- name: create ec2 instance and route53 record
  hosts: local
  connection: local
  vars: 
    image_id: ami-0220d79f3f480ecf5
    security_group: sg-06768f041e8b8b319
    domain_name: yaswanthreddypenchikala.online
    packages: 
    - mongodb
    - redis

  tasks: 
  - name: Launch EC2 Instance
    amazon.aws.ec2_instance:
      name: {{ item }}
      image_id: "{{ image_id }}"
      instance_type: t2.micro
      security_group: "{{ security_group }}"
      count: 1
      state: running
    register: ec2_output
    loop: "{{ packages }}"

  - name: print ec2 output 
    ansible.builtin.debug:
      msg: " {{ ec2_output }}"