- name: Functions in ansible
  hosts: local
  connection: local
  become: yes
  vars: 
    fruits: 
    - key: fruit
      value: apple
    - key: sports
      value: cricket      
  tasks: 
  - name : Printing the varaible
    ansible.builtin.debug: 
      msg: " {{ fruits | items2dict }}"