- name: Functions in ansible
  hosts: local
  connection: local
  become: yes
  vars: 
    employee: yaswanth
  tasks: 
  - name : Printing the varaible
    ansible.builtin.debug: 
      msg: " {{ Name | default('sandeep') }}"