- name: loops in ansible
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: print something using loops
    ansible.builtin.debug: 
      msg: "student name : {{ item }}"
    loop: 
      - yaswanth
      - sandeep
      - rupesh
      - sreedhar