- name: understanding varaiables
  hosts: localhost
  connection : local
  vars: 
    Name : yaswanth
    Designation : software engineer
    Company : HCL
  tasks: 
  - name : prirnting varaiables 
    ansible.builtin.debug: 
      msg: "The student name is {{ Name }} . He works as a {{ Designation }} in {{ Company }}"